There are some files need to be created on all app servers in Stratos DC. 
Nautilus DevOps team want these files to be owned by user root only, however they also want that app specific user must have some set of permissions on these files. 
These all tasks must be done using Ansible only, so accordingly they need to create a playbook. 
Below you can find more information about the task.

Create a playbook.yml under /home/thor/ansible on jump host, an inventory file is already present under /home/thor/ansible on Jump Server itself.
1.	Create an empty file blog.txt under /opt/security/ directory on app server 1. 
    Set some acl properties for this file. Using acl provide read '(r)' permissions to group tony (i.e entity is tony and etype is group).
2.	Create an empty file story.txt under /opt/security/ directory on app server 2. 
    Set some acl properties for this file. Using acl provide read + write '(rw)' permissions to user steve (i.e entity is steve and etype is user).
3.	Create an empty file media.txt under /opt/security/ on app server 3. 
    Set some acl properties for this file. Using acl provide read + write '(rw)' permissions to group banner (i.e entity is banner and etype is group).
Note: Validation will try to run playbook using command ansible-playbook -i inventory playbook.yml so please make sure playbook works this way, without passing any extra arguments.


# Manage ACL using Ansible from KodeKloud
---
- hosts: stapp01
  become: yes
  name: play1
  tasks:
  - name: Create File
    file:
          path: /opt/data/blog.txt
          state: touch
  - name:
    acl:
          path: /opt/data/blog.txt
          entity: tony
          etype: group
          permissions: r
          state: present

- hosts: stapp02
  become: yes
  name: play2
  tasks:
  - name: Create File
    file:
          path: /opt/data/story.txt
          state: touch
  - name:
    acl:
          path: /opt/data/story.txt
          entity: steve
          etype: user
          permissions: rw
          state: present

- hosts: stapp03
  become: yes
  name: play3
  tasks:
  - name: Create File
    file:
          path: /opt/data/media.txt
          state: touch
  - name:
    acl:
          path: /opt/data/media.txt
          entity: banner
          etype: group
          permissions: rw
          state: present
