# There is data on all app servers in Stratos DC. The Nautilus development team shared some requirement with the DevOps team to alter some of the data as per recent changes. 
# The DevOps team is working to prepare an Ansible playbook to accomplish the same. Below you can find more details about the task.
# Create a playbook.yml under /home/thor/ansible on jump host; an inventory is already place under /home/thor/ansible on Jump host itself.
# 1.	We have a file /opt/finance/blog.txt on app server 1. Using Ansible replace module replace string xFusionCorp to Nautilus in that file.
# 2.	We have a file /opt/finance/story.txt on app server 2. Using Ansiblereplace module replace string Nautilus to KodeKloud in that file.
# 3.	We have a file /opt/finance/media.txt on app server 3. Using Ansible replace module replace string KodeKloud to xFusionCorp Industries in that file.
# Note: Validation will try to run playbook using command ansible-playbook -i inventory playbook.yml so please make sure playbook works this way, 
# without passing any extra arguments.

---
- hosts: stapp01
  become: yes
  name: play1
  tasks:
  - name: Replace /opt/finance/blog.txt
	replace: 
    path: /opt/finance/blog.txt
    regexp: 'xFusionCorp'
    replace: 'Nautilus'

- hosts: stapp02
  become: yes
  name: play2
  tasks:
  - name: Replace /opt/finance/story.txt
    replace:
    path: /opt/finance/story.txt
    regexp: 'Nautilus'
    replace: 'KodeKloud'

- hosts: stapp03
  become: yes
  name: play3
  tasks:
  - name: Replace /opt/finance/media.txt
    replace:
    path: /opt/finance/media.txt
    regexp: 'KodeKloud'
    replace: 'xFusionCorp Industries'
