# The Nautilus DevOps team want to install and set up a simple httpd web server on all app servers in Stratos DC. 
# They also want to deploy a sample web page using Ansible only. 
# Therefore, prepare the required playbook to complete this task. Find more details about the task below.
# We already have an inventory file under /home/thor/ansible on jump host. Create a playbook.yml under /home/thor/ansible on jump host itself.
# 1.	Using the playbook install httpd web server on all app servers, and make sure its service is up and running.
# 2.	Create a file /var/www/html/index.html with content:
# This is a Nautilus sample file, created using Ansible!
# 3.	Using lineinfile Ansible module add some more content in /var/www/html/index.html file. Below is the content:
# Welcome to xFusionCorp Industries!
# Also make sure this new line is added at the top of the file.
# 4.	The /var/www/html/index.html file's user and group owner should be apache on all app servers.
# 5.	The /var/www/html/index.html file's permissions should be 0644 on all app servers.
# Note: Validation will try to run playbook using command ansible-playbook -i inventory playbook.yml so please make sure playbook works this way, 
# without passing any extra arguments.


---
- name: Install Apache and modify index.html
  hosts: all
  become: true
  tasks:
  - name: install the latest version of Apache
    yum:
       name: httpd
       state: latest
  - name: Create file and add content
    copy:
       content: "This is a Nautilus sample file, created using Ansible!"
       dest: "/var/www/html/index.html"
       backup: yes
       owner: apache
       group: apache
       mode: 0644  
  - name: Insert additional content
    lineinfile:
       path: /var/www/html/index.html
       insertbefore: '^T*'
       line: "Welcome to xFusionCorp Industries!"
  - name: Enable service httpd
    service:
       name: httpd
       enabled: yes
  - name: Restart service httpd
    service:
       name: httpd
       state: restarted
...

# SAMPLE INVENTORY FILE

# stapp01 ansible_host=172.16.238.10 ansible_ssh_pass=Ir0nM@n ansible_user=tony
# stapp02 ansible_host=172.16.238.11 ansible_ssh_pass=Am3ric@ ansible_user=steve
# stapp03 ansible_host=172.16.238.12 ansible_ssh_pass=BigGr33n ansible_user=banner

# SAMPLE ansible.cfg

# [defaults]
# host_key_checking = False

