---
- hosts: slave1
  - name: MongoDB - Import public key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EA312927

  - name: MongoDB - Add repository
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/3.4 multiverse
      state: present

  - name: MongoDB - Install MongoDB
    apt:
      name: mongodb-org
      state: present
      update_cache: yes
    become: sudo

  - name: Start mongod
    shell: "mongod &"

